/**
 * A separate module containing all constants for redux related modules.
 */

const GET_TODOLIST = 'GET_TODOLIST';

const GET_TODOLIST_SUCCESS = 'GET_TODOLIST_SUCCESS';

const GET_TODOLIST_FAILURE = 'GET_TODOLIST_FAILURE';


const DELETE_TODO = 'DELETE_TODO';

const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';

const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE';


const UPLOAD_TODO = 'UPLOAD_TODO';

const UPLOAD_TODO_SUCESS = 'UPLOAD_TODO_SUCESS';

const UPLOAD_TODO_FAILURE = 'UPLOAD_TODO_FAILURE';


const SNIP_TODO = 'SNIP_TODO';

const SNIP_TODO_SUCESS = 'SNIP_TODO_SUCESS';

const SNIP_TODO_FAILURE = 'SNIP_TODO_FAILURE';


const SET_EDITED_TODO = 'SET_EDITED_TODO';

const SET_SELECTED_TODO = 'SET_SELECTED_TODO';

const SET_ALERT_NAME = 'SET_ALERT_NAME';

const SET_EDITOR = 'SET_EDITOR';


export {
  
  GET_TODOLIST,
  GET_TODOLIST_SUCCESS,
  GET_TODOLIST_FAILURE,

  DELETE_TODO,
  DELETE_TODO_SUCCESS,
  DELETE_TODO_FAILURE,

  UPLOAD_TODO,
  UPLOAD_TODO_SUCESS,
  UPLOAD_TODO_FAILURE,

  SNIP_TODO,
  SNIP_TODO_SUCESS,
  SNIP_TODO_FAILURE,

  SET_EDITED_TODO,
  SET_SELECTED_TODO,
  SET_ALERT_NAME,
  SET_EDITOR,
};